import unittest
from chargepointdetails_to_S3 import process_json_to_csv


class TestDataProcessing(unittest.TestCase):
    def setUp(self):
        # Load sample data from a file or API
        self.data = {"Scheme":{"SchemeCode":"NA","SchemeData":{"OrganisationName":"NA","Website":"NA","TelephoneNo":"NA"}}, "ChargeDevice":[
            {
			    'ChargeDeviceId': '5039c877840015a6f06d36be4b81dd3b', 'ChargeDeviceRef': 'INS75773', 'ChargeDeviceName': 'DURHAM 2', 'ChargeDeviceText': None, 'ChargeDeviceLocation': {'Latitude': '54.783942', 'Longitude': '-1.535497', 'Address': {'SubBuildingName': None, 'BuildingName': 'Bannatyne Health Club & Spa', 'BuildingNumber': '', 'Thoroughfare': '14 Eden Terrace', 'Street': '', 'DoubleDependantLocality': None, 'DependantLocality': None, 'PostTown': 'Durham', 'County': 'Durham', 'PostCode': 'DH1 2HJ', 'Country': 'gb', 'UPRN': ''}, 'LocationShortDescription': None, 'LocationLongDescription': 'Station can be found within the car park of Bannatyne Gym. This station is available for all public use.'}, 'ChargeDeviceManufacturer': 'Other', 'ChargeDeviceModel': 'CPE200T-S-CHD-CMB', 'PublishStatusID': '1', 'DateCreated': '2018-01-10 15:12:58', 'DateUpdated': '2020-02-18 07:09:30', 'Attribution': 'InstaVolt Ltd', 'DateDeleted': 'n/a', 'Connector': [{'ConnectorId': 'CHA003-020-02', 'ConnectorType': 'JEVS G105 (CHAdeMO) DC', 'RatedOutputkW': '50.0', 'RatedOutputVoltage': '400', 'RatedOutputCurrent': '125', 'ChargeMethod': 'DC', 'ChargeMode': '4', 'ChargePointStatus': 'In service', 'TetheredCable': '1', 'Information': '', 'Validated': '0'}, {'ConnectorId': 'CCS003-020-02', 'ConnectorType': 'CCS Type 2 Combo (IEC62196)', 'RatedOutputkW': '50.0', 'RatedOutputVoltage': '400', 'RatedOutputCurrent': '125', 'ChargeMethod': 'DC', 'ChargeMode': '4', 'ChargePointStatus': 'In service', 'TetheredCable': '1', 'Information': '', 'Validated': '0'}], 'DeviceOwner': {'OrganisationName': 'InstaVolt Ltd', 'SchemeCode': 'INSTAV', 'Website': 'instavolt.co.uk', 'TelephoneNo': '01256 305900'}, 'DeviceController': {'OrganisationName': 'InstaVolt Ltd', 'SchemeCode': 'INSTAV', 'Website': 'instavolt.co.uk', 'TelephoneNo': '01256 305900'}, 'DeviceAccess': [], 'DeviceNetworks': 'InstaVolt Ltd', 'ChargeDeviceStatus': 'In service', 'PublishStatus': 'Published', 'DeviceValidated': '0', 'RecordModerated': 'Y', 'RecordLastUpdated': '2019-08-11 15:28:02', 'RecordLastUpdatedBy': 'InstaVolt Ltd', 'PaymentRequiredFlag': True, 'PaymentDetails': '£0.35p/KWh or a maximum of £18 per session', 'SubscriptionRequiredFlag': False, 'SubscriptionDetails': '', 'ParkingFeesFlag': False, 'ParkingFeesDetails': '', 'ParkingFeesUrl': '', 'AccessRestrictionFlag': False, 'AccessRestrictionDetails': '', 'PhysicalRestrictionFlag': False, 'PhysicalRestrictionText': '', 'OnStreetFlag': False, 'LocationType': 'Leisure centre', 'Bearing': None, 'Accessible24Hours': False
            },
            {
                'ChargeDeviceId': '897fd9c0f53fa1d2d4cedaf50ce5b4b8', 'ChargeDeviceRef': 'GP10489', 'ChargeDeviceName': 'Civic Offices Bridge Street', 'ChargeDeviceText': None, 'ChargeDeviceLocation': {'Latitude': '51.451876', 'Longitude': '-0.972436', 'Address': {'SubBuildingName': None, 'BuildingName': '', 'BuildingNumber': '', 'Thoroughfare': 'Bridge Street', 'Street': 'Arnold', 'DoubleDependantLocality': None, 'DependantLocality': None, 'PostTown': 'Reading', 'County': 'Berkshire', 'PostCode': 'RG1 2LU', 'Country': 'gb', 'UPRN': ''}, 'LocationShortDescription': None, 'LocationLongDescription': ''}, 'ChargeDeviceManufacturer': 'APT', 'ChargeDeviceModel': 'Raption', 'PublishStatusID': '1', 'DateCreated': '2018-02-27 12:44:04', 'DateUpdated': '2020-01-06 14:50:21', 'Attribution': 'The GeniePoint Network', 'DateDeleted': 'n/a', 'Connector': [{'ConnectorId': '1', 'ConnectorType': 'Type 2 Mennekes (IEC62196)', 'RatedOutputkW': '22.0', 'RatedOutputVoltage': '400', 'RatedOutputCurrent': '32', 'ChargeMethod': 'Three Phase AC', 'ChargeMode': '3', 'ChargePointStatus': 'In service', 'TetheredCable': '0', 'Information': '', 'Validated': '0'}, {'ConnectorId': '3', 'ConnectorType': 'CCS Type 2 Combo (IEC62196)', 'RatedOutputkW': '22.0', 'RatedOutputVoltage': '400', 'RatedOutputCurrent': '60', 'ChargeMethod': 'DC', 'ChargeMode': '4', 'ChargePointStatus': 'In service', 'TetheredCable': '1', 'Information': '', 'Validated': '0'}, {'ConnectorId': '2', 'ConnectorType': 'JEVS G105 (CHAdeMO) DC', 'RatedOutputkW': '22.0', 'RatedOutputVoltage': '400', 'RatedOutputCurrent': '60', 'ChargeMethod': 'DC', 'ChargeMode': '4', 'ChargePointStatus': 'In service', 'TetheredCable': '1', 'Information': '', 'Validated': '0'}], 'DeviceOwner': {'OrganisationName': 'Equans EV Solutions', 'SchemeCode': 'evsolut', 'Website': 'https://www.equans.co.uk/ev-solutions', 'TelephoneNo': '02035984087'}, 'DeviceController': {'OrganisationName': 'Equans EV Solutions', 'SchemeCode': 'C222', 'Website': 'https://www.equans.co.uk/ev-solutions', 'TelephoneNo': '02035984087'}, 'DeviceAccess': [], 'DeviceNetworks': 'The GeniePoint Network', 'ChargeDeviceStatus': 'In service', 'PublishStatus': 'Published', 'DeviceValidated': '0', 'RecordModerated': 'Y', 'RecordLastUpdated': '2019-10-12 16:57:11', 'RecordLastUpdatedBy': 'Deprecated 2', 'PaymentRequiredFlag': True, 'PaymentDetails': 'visit www.geniepoint.co.uk', 'SubscriptionRequiredFlag': False, 'SubscriptionDetails': '', 'ParkingFeesFlag': False, 'ParkingFeesDetails': '', 'ParkingFeesUrl': 'visit www.geniepoint.co.uk', 'AccessRestrictionFlag': False, 'AccessRestrictionDetails': '', 'PhysicalRestrictionFlag': False, 'PhysicalRestrictionText': '', 'OnStreetFlag': False, 'LocationType': 'Public car park', 'Bearing': None, 'Accessible24Hours': False
            },
            {
                "ChargeDeviceId":"52b738b303d90a884137546353e09ebb","ChargeDeviceRef":"SC23","ChargeDeviceName":"Little Donegall Street, Belfast (Socket ","ChargeDeviceText":"On-street charging point on Little Donegall Street, usual parking restrictions and charges apply","ChargeDeviceLocation":{"Latitude":"54.604646","Longitude":"-5.931866","Address":{"SubBuildingName":None,"BuildingName":"","BuildingNumber":"128","Thoroughfare":"Little Donegall Street","Street":"","DoubleDependantLocality":None,"DependantLocality":None,"PostTown":"Belfast","County":"County Antrim","PostCode":"BT1 2JD","Country":"gb","UPRN":None},"LocationShortDescription":"On-street charging point on Little Donegall Street, usual parking restrictions and charges apply","LocationLongDescription":"On-street charging point on Little Donegall Street, usual parking restrictions and charges apply (Socket 2)"},"ChargeDeviceManufacturer":None,"ChargeDeviceModel":"","PublishStatusID":"1","DateCreated":"2012-04-12 14:00:01","DateUpdated":"2021-07-07 09:40:22","Attribution":"ecars ESB","DateDeleted":"n\/a","Connector":[{"ConnectorId":"LBBN24000980","ConnectorType":"Type 2 Mennekes (IEC62196)","RatedOutputkW":"22.0","RatedOutputVoltage":"400","RatedOutputCurrent":"32","ChargeMethod":"Three Phase AC","ChargeMode":"3","ChargePointStatus":"In service","TetheredCable":"0","Information":None,"Validated":"0"},{"ConnectorId":"LBBN24000981","ConnectorType":"Type 2 Mennekes (IEC62196)","RatedOutputkW":"22.0","RatedOutputVoltage":"400","RatedOutputCurrent":"32","ChargeMethod":"Three Phase AC","ChargeMode":"3","ChargePointStatus":"In service","TetheredCable":"0","Information":None,"Validated":"0"}],"DeviceOwner":{"OrganisationName":"ecars ESB","SchemeCode":"NIE","Website":"https:\/\/www.esb.ie\/ecars","TelephoneNo":"00353 1258 3799"},"DeviceController":{"OrganisationName":"ecars ESB","SchemeCode":"NIE","Website":"https:\/\/www.esb.ie\/ecars","TelephoneNo":"00353 1258 3799"},"DeviceAccess":{"Open24Hours":True},"DeviceNetworks":"ecars ESB","ChargeDeviceStatus":"In service","PublishStatus":"Published","DeviceValidated":"0","RecordModerated":"Y","RecordLastUpdated":"2021-07-06 11:24:08","RecordLastUpdatedBy":"EB Charging","PaymentRequiredFlag":True,"PaymentDetails":"","SubscriptionRequiredFlag":True,"SubscriptionDetails":"","ParkingFeesFlag":False,"ParkingFeesDetails":"","ParkingFeesUrl":None,"AccessRestrictionFlag":False,"AccessRestrictionDetails":"","PhysicalRestrictionFlag":False,"PhysicalRestrictionText":"","OnStreetFlag":True,"LocationType":"On-street","Bearing":None,"Accessible24Hours":True
            }
        ]}
		
    def test_output_columns_list(self):
        expected_output = 'ChargeDeviceManufacturer,LocationType,ChargeDeviceModel,PostCode,MonthUpdated,Count\r\nAPT,Public car park,Raption,RG1 2LU,2020-01,1\r\nOther,Leisure centre,CPE200T-S-CHD-CMB,DH1 2HJ,2020-02,1\r\n'
        correct_output = process_json_to_csv(self.data)
        self.assertEqual(expected_output, correct_output)
		
if __name__ == '__main__':
    unittest.main()